#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/jovyan/nrn-7.7"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/jovyan/nrn-7.7/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/jovyan/work/NeuroML_Examples/Rocher/LEMSFILES2/x86_64/.libs/libnrnmech.so" "$@"
